/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/A2moeiNdum3
 */
import Link from "next/link"

export function Site() {
  return (
    <div className="w-full min-h-screen bg-slate-900 text-white">
      <section className="w-full max-w-[2000px] min-h-screen px-16 mx-auto">
        <div className="md:flex md:space-x-6">
          <section
            className="md:w-1/2 flex flex-col items-start justify-start space-y-8 text-left mt-16 md:mt-32"
            id="home"
          >
            <h1 className="text-6xl md:text-7xl font-extrabold tracking-tighter bg-clip-text text-transparent bg-gradient-to-r from-purple-500 to-blue-500 mb-4">
              Hi, I'm Jared.
            </h1>
            <p className="max-w-[700px] text-xl md:text-2xl text-slate-400 mb-8">
              I'm a software engineer developing the future of video
              <Link className="font-bold mx-2" href="https://twitter.com/Microsoft">
                @microsoft
              </Link>
              through AI experiences. React is my jam.
            </p>
            <p className="max-w-[700px] text-xl md:text-2xl text-slate-400 mb-8">
              I created
              <Link className="font-bold mx-2" href="https://pokestats.live">
                pokestats.live
              </Link>
              serving as the standard for live Pokémon tournament analytics, driving 50,000 montly visitors.
            </p>
            <p className="max-w-[700px] text-xl md:text-2xl text-slate-400">
              When I'm not centering divs, I compete in the Pokémon TCG, currently standing in the top 32 players in
              North America!
            </p>
          </section>
          <section className="md:w-1/2 mt-16 md:mt-32 space-y-8" id="resume">
            <div className="grid grid-cols-3 gap-6 max-w-[700px] mx-auto text-lg md:text-xl text-slate-400">
              <div className="col-span-1 font-bold text-slate-500">2022 - Present</div>
              <div className="col-span-2 space-y-2">
                <h3 className="text-2xl font-bold tracking-tighter">Software Engineer - Microsoft</h3>
                <p className="text-slate-400">
                  Developed UI for Stream's AI companion, Copilot, to quickly extract meaningful information and
                  insights from video. Optimized and maintained experiences for viewing and editing video
                  transcriptions.
                </p>
              </div>
              <div className="col-span-1 font-bold text-slate-500">2020 - 2022</div>
              <div className="col-span-2 space-y-2">
                <h3 className="text-2xl font-bold tracking-tighter">Front-End Engineer - Amazon</h3>
                <p className="text-slate-400">
                  Delivered user interfaces for analyzing business risks and opportunities, introduced frameworks to
                  boost performance and maintainability and created best practices for developing front-end. Led
                  development for a comprehensive design library for business intelligence, unifying teams across Amazon
                  with top-tier data and negotiation experiences.
                </p>
              </div>
              <div className="col-span-1 font-bold text-slate-500">Summer 2019</div>
              <div className="col-span-2 space-y-2">
                <h3 className="text-2xl font-bold tracking-tighter">SDE Internship - Amazon</h3>
                <p className="text-slate-400">
                  Developed an end-to-end utility that enables deeper analysis into business regression and performance
                  optimization.
                </p>
              </div>
            </div>
          </section>
        </div>
        <section className="py-24 md:py-48 lg:py-64 xl:py-36 flex flex-col items-start justify-center" id="contact">
          <h2 className="text-4xl md:text-6xl font-extrabold tracking-tighter bg-clip-text text-transparent bg-gradient-to-r from-purple-500 to-blue-500 mb-8">
            Let's Connect.
          </h2>
          <Link
            className="py-3 px-6 rounded-full border-2 border-blue-500 text-blue-500 text-lg md:text-xl font-bold tracking-wide hover:bg-blue-500 hover:text-slate-900 transition-colors duration-200"
            href="https://twitter.com/jgrimesey"
          >
            <IconTwitter className="h-6 w-6 inline-block mr-2" />
            Connect on Twitter
          </Link>
        </section>
      </section>
    </div>
  )
}


function IconTwitter(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
